[package]
name = "signal-rss"
version = "0.4.2"
edition = "2024"

[dependencies]
atom_syndication = "0.12.7"
base64 = "0.22.1"
chrono = "0.4.40"
dbus = "0.9.7"
reqwest = "0.12.15"
rss = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
