[package]
name = "rssi"
version = "0.1.0"
edition = "2024"

[dependencies]
atom_syndication = "0.12.7"
base64 = "0.22.1"
chrono = "0.4.40"
dbus = "0.9.7"
json = "0.12.4"
reqwest = "0.12.15"
rss = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
